---

- name: Configure Zabbix packages
  ansible.builtin.include_tasks: zabbix_packages_config.yml
  when: zabbix_install

- name: Configure Zabbix Server service
  ansible.builtin.include_tasks: zabbix_server_config.yml
  when: zabbix_install

- name: Add Zabbix Hosts
  ansible.builtin.include_tasks: zabbix_hosts_add.yml
  when: zabbix_hosts_add
