- name: Set credentials to access Zabbix Server API
  ansible.builtin.set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix



- name: Create multiple hosts or rewrite existing host info (Zabbix <= 7.0)
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "zabbix" 
  become: false
  community.zabbix.zabbix_host:
    host_name: "{{ item.host_name }}"
    visible_name: "{{ item.visible_name }}"
    description: "{{ item.description }}"
    status: enabled
    state: present
    link_templates:
      - Linux by Zabbix agent
    host_groups:
      - Linux servers
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ item.ip }}"
        port: "10051"
  loop:
    - { host_name: "Biuro", visible_name: "Biuro", description: "Serwer Biurowy", ip: "192.168.30.100" }
    - { host_name: "Programowanie", visible_name: "Programowanie", description: "Serwer Deweloperski", ip: "192.168.40.101" }
    - { host_name: "Baza-Danych", visible_name: "", description: "Serwer z Bazą danych", ip: "192.168.40.100" }