- name: Check if dev_table exists in the database
  ansible.builtin.shell: |
    sudo -u postgres psql -d {{ db_name }} -tAc "SELECT 1 FROM information_schema.tables WHERE table_name='dev_table';"
  register: table_check
  changed_when: false 

- name: Create a table in the database if it does not exist
  ansible.builtin.shell: |
    sudo -u postgres psql -d {{ db_name }} -c "
    CREATE TABLE IF NOT EXISTS dev_table (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    "
  when: table_check.stdout.strip() == ""
  register: table_created