- name: Check if PostgreSQL user exists
  ansible.builtin.shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user }}';"
  register: user_check
  changed_when: false

- name: Create PostgreSQL user
  ansible.builtin.shell: |
    sudo -u postgres psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ postgresql_user_pass }}';"
  when: user_check.stdout.strip()==""
  register: user_created
