- name: Check if PostgreSQL database exists
  ansible.builtin.shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ db_name }}';"
  register: db_check
  changed_when: false 

- name: Create PostgreSQL database
  ansible.builtin.shell: |
    sudo -u postgres psql -c "CREATE DATABASE {{ db_name }} OWNER {{ db_user }};"
  when: db_check.stdout.strip() == ""
  register: db_created