---
- name: Download Zabbix repository package (7.0)
  ansible.builtin.get_url:
    url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb"
    dest: "/tmp/zabbix-release_latest_7.0+ubuntu22.04_all.deb"

- name: Install Zabbix repository package (7.0)
  ansible.builtin.apt:
    deb: "/tmp/zabbix-release_latest_7.0+ubuntu22.04_all.deb"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Zabbix Agent 2 and plugins
  ansible.builtin.apt:
    name: 
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present

- name: Deploy Zabbix Agent configuration with dynamic hostname
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
      

- name: Restart Zabbix Agent 2 service
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted

- name: Enable Zabbix Agent 2 service at boot
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: yes

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow Zabbix Agent port (10050)
  ansible.builtin.ufw:
    rule: allow
    port: 10050
    proto: tcp

- name: Allow Zabbix Server port (10051)
  ansible.builtin.ufw:
    rule: allow
    port: 10051
    proto: tcp