install_dev_db_software: true
create_database: true
config_docker: true
zabbix_agent_install: true
db_user: admin_dev
db_name: dev_database

container_count: 4
default_container_name: docker
default_container_image: ubuntu
default_container_command: sleep 1