---
- name: Install necessary applications and packages on the office workstations.
  hosts: office_group
  become: yes  # sudo
  vars_files:
    - vault.yml
  tasks:
    - name: Ensure system is up to date.
      ansible.builtin.apt:
        update_cache: yes

    - name: Ensure necessary packages are installed.
      ansible.builtin.apt:
        name:
          - git
          - vim
          - htop
          - curl
          - wget
        state: present
    # Install applications available in Debian repositories
    - name: Install LibreOffice, Thunderbird and a PDF viewer
      ansible.builtin.apt:
        name:
          - libreoffice          
          - thunderbird                  
          - evince               # PDF viewer (alternative: Okular)
        state: present
     # Install Snap (required for non-repository applications)
    - name: Install Snap package manager
      ansible.builtin.apt:
        name: snapd
        state: present
    - name: Enable and start Snap service
      ansible.builtin.service:
        name: snapd
        state: started
        enabled: yes
     # Install Microsoft Teams using Snap
    - name: Install Microsoft Teams
      community.general.snap:
        name: teams-for-linux
        state: present
     # Install Zoom using Snap
    - name: Install Zoom
      community.general.snap:
        name: zoom-client
        state: present
    # Install Wekan (Trello alternative)
    - name: Install Wekan (Trello alternative)
      community.general.snap:
        name: wekan
        state: present
    # Install Firefox
    - name: Install Firefox
      community.general.snap:
        name: firefox
        state: present
- name: Install necessary packages on the developer and database workstations.
  hosts: dev_group
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Ensure system is up to date.
      ansible.builtin.apt:
        update_cache: yes
    - name: Ensure necessary packages are installed.
      ansible.builtin.apt:
        name:
          - git
          - vim
          - htop
          - curl
          - wget
        state: present
- name: Install necessary applications and packages on the developer workstations.
  hosts: dev
  become: yes
  vars_files:
    - vault.yml
  tasks:
    # Install GCC (C/C++ compiler)
    - name: Install GCC and build essentials
      ansible.builtin.apt:
        name:
          - gcc
          - g++
          - make
        state: present
    
    # Remove Snap restriction in Mint
    - name: Remove Snap restriction in Mint
      ansible.builtin.file:
        path: /etc/apt/preferences.d/nosnap.pref
        state: absent

    # Install Snap (required for non-repository applications)
    - name: Install Snap package manager
      ansible.builtin.apt:
        name: snapd
        state: present
    - name: Enable and start Snap service
      ansible.builtin.service:
        name: snapd
        state: started
        enabled: yes

    # Install DBeaver (Database Manager)
    - name: Install DBeaver
      community.general.snap:
        name: dbeaver-ce
        state: present

    # Install PyCharm (using Snap)
    - name: Install PyCharm
      community.general.snap:
        name: pycharm-community
        state: present
        classic: true

    # Install VS Code
    - name: Add Microsoft GPG key for VS Code
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present

    - name: Install VS Code
      ansible.builtin.apt:
        name: code
        state: present

    # Add repository for the latest Java (Adoptium Temurin)
    - name: Add Adoptium GPG key
      ansible.builtin.apt_key:
        url: https://packages.adoptium.net/artifactory/api/gpg/key/public
        state: present

    - name: Add Adoptium repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.adoptium.net/artifactory/deb jammy main"
        state: present

    # Install the latest OpenJDK (Java, includes javac)
    - name: Install the latest OpenJDK (Java with javac)
      ansible.builtin.apt:
        name: temurin-20-jdk  
        state: present

    # Verify installation of javac (optional check)
    - name: Check if javac is installed
      ansible.builtin.command:
        cmd: javac -version
      register: javac_version
      failed_when: javac_version.rc != 0

    # Install PostgreSQL
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present
    
    # Install IntelliJ IDEA Community Edition
    - name: Install IntelliJ IDEA Community Edition
      community.general.snap:
        name: intellij-idea-community
        state: present
        classic: true